#!/usr/bin/env sh
#
#
# wm independent hotkeys
#

# terminal emulator
super + Return
  kitty

# program launcher
super + {_,shift} + p
  rofi -show {drun, window} -show-icons

# make sxhkd reload its configuration files:
super + Escape
    pkill -USR1 -x sxhkd

#
# bspwm hotkeys
#

super + alt + {_,shift + }{1-9,0}
    bspc {desktop -f, window -d} $(bspc query -M -m)/{a,b,c}

# Next monitor
alt + w
    bspc monitor -f next

# Restart/quit bspwm
super + alt + {_, shift} + Escape
    bspc {wm -r, quit}

# close and kill
super + {_,shift + }w
    bspc node -{c,k}

# alternate between the tiled and monocle layout
super + o
    bspc desktop -l next

# send the newest marked node to the newest preselected node
super + y
    bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
super + g
    bspc node -s biggest

# Swap the current node with preselected node
super + s
    bspc node -n 'newest.!automatic.local'

#
# state/flags
#

# set the window state
super + {t, shift + t, shift + f, f}
    bspc node -t {tiled, psuedo_tiled, floating, fullscreen}

# set the node flags {marked,locked,sticy,private}
super + ctrl + {m,x,y,z}
    bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction
super + {_,shift + }{m,n,e,i}
    bspc node -{f,s} {west,south,north,east}

# focus the node for the given path jump
# super + {p,b,comma,per od}
#     bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }Tab
    bspc node -f {next,prev}.local.leaf

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
    bspc desktop -f {prev,next}.local.leaf

# focus the last node/desktop
# super + {grave,Tab}
    # bspc {node,desktop} -f last

# focus the older or newer node in the focus history
# super + {o,i}
#     bspc wm -h off; \
#     bspc node {older,newer} -f; \
#     bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
    bspc {desktop -f,node -d} 'focused:^{1-9,10}'

#
# preselect
#

# preselect the direction
super + ctrl + {m,n,e,i}
    bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
    bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
    bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
    bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# rotate tree clock/c.clock-wise
super + {r,R}
  bspc node @/ -R {90,-90}

# expand a window by moving one of its side outward
super + alt + {m,n,e,i}
    bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# contract a window by moving one of its side inward
super + alt + shift + {m,n,e,i}
    bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}

# move a floating window
super + {Left,Down,Up,Right}
    bspc node -v {-20 0,0 20,0 -20,20 0}

# set window position to bottom right
super + v
    ~/.config/sxhkd/scripts/move_window.sh 3

#
# Media controls
#

XF86AudioPlay
  playerctl play-pause

XF86AudioStop
  playerctl stop

XF86AudioNext
  playerctl next

XF86AudioPrev
  playerctl previous

XF86AudioMute
  pactl set-sink-mute 0 toggle

XF86AudioRaiseVolume
  pactl set-sink-volume 0 +5%

XF86AudioLowerVolume
  pactl set-sink-volume 0 -5%

#
# Programs
#

# Emacs client
super + c
  emacsclient -s doom_server -c

# Emacs nonclient
super + shift + c
  emacs

# Emacs server
super + alt + shift + c
  emacs --bg-daemon=doom_server

# super + ctrl + y
  $HOME/.config/sxhkd/scripts/doom_capture -k j

# Firefox
super + b
  firefox

# Termite drop
super + ctrl + s
  tdrop -m -h 33% -w 45% -x 1% -y 5% -n 1000 -a kitty

# Ranger drop
super + ctrl + r
  tdrop -m -h 33% -w 45% -x 54% -y 5% -n 2000 -a -f '-e ranger' kitty

# Htop drop
super + ctrl + p
  tdrop -m -h 33% -w 45% -x 1% -y 66% -n 3000 -a -f '-e htop' kitty

# Audia control drop
super + ctrl + v
  tdrop -m -h 33% -w 45% -x 54% -y 66% -n 4000 -a -f '-e pulsemixer' kitty

# Bitwarden rofi, autolock after 1hour
super + shift + o
  bwmenu --auto-lock 86400

# Screenshot utility: +shift for save
super + {_, shift} + Print
  xfce4-screenshooter {-c -r,-r}

# Lock
super + ctrl + alt + l
  dm-tool lock


#
# UI
#

# Increase gap
super + plus
  /home/eethern/.config/sxhkd/scripts/gap_inc.sh

# Decrease gap
super + minus
  /home/eethern/.config/sxhkd/scripts/gap_dec.sh

# Increase border
super + shift + plus
  /home/eethern/.config/sxhkd/scripts/border_inc.sh

# Decrease border
super + shift + minus
  /home/eethern/.config/sxhkd/scripts/border_dec.sh
