#!/usr/bin/env sh

# Restart/quit bspwm
super + alt + {_, shift} + Escape
    bspc {wm -r, quit}

# close and kill
super + {_,shift + }w
    bspc node -{c,k}

# alternate between the tiled and monocle layout
super + z
    bspc desktop -l next

super + o; m
  ~/.config/bspwm/mons.sh select

# send the newest marked node to the newest preselected node
# super + y
#     bspc node newest.marked.local -n newest.!automatic.local

# swap the current node and the biggest node
# super + g
#     bspc node -s biggest

# Swap the current node with preselected node
super + s
    bspc node -n 'newest.!automatic.local'

#
# state/flags
#

# set the window state
super + {t, shift + t, shift + f, f}
    bspc node -t {tiled, psuedo_tiled, floating, fullscreen}

# set the node flags {marked,locked,sticky,private}
super + ctrl + {k,x,y,z}
    bspc node -g {marked,locked,sticky,private}

#
# focus/swap
#

# focus the node in the given direction, or an empty monitor
# src: https://www.reddit.com/r/bspwm/comments/jpiopk/focusing_empty_monitor_with_a_keybind/
super + {m,n,e,i}
    dir={west,south,north,east}; bspc node "$dir" -f || bspc monitor "$dir" -f

super + {Left,Down,Up,Right}
    dir={west,south,north,east}; bspc node "$dir" -f || bspc monitor "$dir" -f

# Swap a node in the given direction. If across a monitor, simply move it to that monitor
super + shift + {m,n,e,i}
    dir={west,south,north,east}; \
    bspc node -s "$dir.local" --follow \
        || bspc node -m "$dir" --follow

super + shift + {Left,Down,Up,Right}
    dir={west,south,north,east}; \
    bspc node -s "$dir.local" --follow \
        || bspc node -m "$dir" --follow

# focus the node for the given path jump
super + {u,b,comma,period}
    bspc node -f @{parent,brother,first,second}

# focus the next/previous node in the current desktop
super + {_,shift + }Tab
    bspc node -f {next,prev}.local.leaf

# focus the next/previous desktop in the current monitor
super + bracket{left,right}
    bspc desktop -f {prev,next}.local.leaf

# focus the last node/desktop
# super + {grave,Tab}
    # bspc {node,desktop} -f last

# focus the older or newer node in the focus history
# super + {o,i}
#     bspc wm -h off; \
#     bspc node {older,newer} -f; \
#     bspc wm -h on

# focus or send to the given desktop
super + {_,shift + }{1-9,0}
    bspc {desktop -f,node -d} 'focused:^{1-9,10}'

# focus the leaf node corresponding to the number on the focused desktop
alt + super + {1-9,0}
    bspc node -f $(bspc query -N -n .leaf -d focused | sed -n "{1-9,0} p")
#
# preselect
#

# preselect the direction
super + ctrl + {m,n,e,i}
    bspc node -p {west,south,north,east}

super + ctrl + {Left,Down,Up,Right}
    bspc node -p {west,south,north,east}

# preselect the ratio
super + ctrl + {1-9}
    bspc node -o 0.{1-9}

# cancel the preselection for the focused node
super + ctrl + space
    bspc node -p cancel

# cancel the preselection for the focused desktop
super + ctrl + shift + space
    bspc query -N -d | xargs -I id -n 1 bspc node id -p cancel

#
# move/resize
#

# rotate tree clock/c.clock-wise
super + {r,R}
  bspc node @/ -R {90,-90}

# expand a window by moving one of its side outward
super + alt + {m,n,e,i}
    bspc node -z {left -80 0,bottom 0 80,top 0 -80,right 80 0}

super + alt + {Left,Down,Up,Right}
    bspc node -z {left -80 0,bottom 0 80,top 0 -80,right 80 0}

# contract a window by moving one of its side inward
super + alt + shift + {m,n,e,i}
    bspc node -z {right -80 0,top 0 80,bottom 0 -80,left 80 0}

super + alt + shift + {Left,Down,Up,Right}
    bspc node -z {right -80 0,top 0 80,bottom 0 -80,left 80 0}
