#!/usr/bin/env bash

~/.config/polybar/scripts/launch.sh
feh --bg-scale ~/Pictures/Wallpapers/ZTWO_wallpaper_1920x1080.png 

current=$(autorandr --current)
notify-send -i display "Display profile: $current"
