#! /bin/sh

inner_gap=5
outer_gap_vert=10
outer_gap_hori=10
bar_compensation=0

bspc config border_width         2
bspc config window_gap           $inner_gap
bspc config top_padding          $((-inner_gap+outer_gap_vert+bar_compensation))
bspc config bottom_padding       $((-inner_gap+outer_gap_vert+bar_compensation))
bspc config left_padding         $((-inner_gap+outer_gap_hori))
bspc config right_padding        $((-inner_gap+outer_gap_hori))
bspc config split_ratio          0.618
bspc config borderless_monocle   true
bspc config single_monocle       false
bspc config focused_border_color "#ad8c79"
bspc config focus_follows_pointer false

# Rules
bspc rule -a Emacs state=tiled
bspc rule -a discord state=tiled desktop=^9 follow=off
bspc rule -a Screenkey manage=off
bspc rule -a rocket.chat+ desktop=^9
bspc rule -a Zathura state=tiled
bspc rule -a termite state=tiled
bspc rule -a Steam desktop=^8 follow=off
bspc config external_rules_command "$HOME/.config/bspwm/rules/spotify.sh"

## Monitors
if [[ "$(hostname)" == "station" ]]; then
    ~/.screenlayout/Layout.sh
    bspc monitor DP-1 -d web code opt1 opt2 opt3 opt4 opt5 opt6 msg music
    bspc monitor DVI-D-0 -d web code opt1 opt2 opt3 opt4 opt5 opt6 msg music
fi

if [[ "$(hostname)" == "shuttle" ]]; then
    bspc monitor eDP1 -d web code opt1 opt2 opt3 opt4 opt5 opt6 msg music
fi
	
if [[ "$(hostname)" == "elx781652zl" ]]; then
    bspc monitor eDP-1 -d web code opt1 opt2 opt3 opt4 opt5 opt6 msg music
fi
	

## Startup
if [ ! -f /tmp/bspwm_startup ]
then
    touch /tmp/bspwm_startup

    feh --bg-scale ~/.dotfiles/.img/space.jpg

    # Background applications
    emacs --bg-daemon=doom_server &
    picom --config ~/.config/picom/picom.conf &
    dunst &
    redshift-gtk &
    sxhkd -c ~/.config/sxhkd/sxhkdrc &

    if [[ "$(hostname)" == "station" ]]; then
        picom --config ~/.config/picom/picom.conf &
        polybar -r station-topbar &
        xmodmap ~/.dotfiles/colemak/colemak-dh-wide.xmodmap
        steam-native &
    fi

    if [[ "$(hostname)" == "shuttle" ]]; then
        picom --config ~/.config/picom/picom.conf &
        polybar -r shuttle-topbar &
        xmodmap ~/.dotfiles/colemak/colemak-dh-ansi.xmodmap
    fi

    if [[ "$(hostname)" == "elx781652zl" ]]; then
	compton &
        polybar -r work-topbar &
        # xmodmap ~/.dotfiles/colemak/colemak-dh-wide.xmodmap
    fi

    # Other applications
    dropbox &
    spotify --force-device-scale-factor=0.75 &
    mullvad-vpn &
    discord-canary &
fi
