#! /bin/bash

inner_gap=5
outer_gap_vert=10
outer_gap_hori=10
bar_compensation=0

bspc config border_width         2
bspc config window_gap           $inner_gap
bspc config top_padding          $((-inner_gap+outer_gap_vert+bar_compensation))
bspc config bottom_padding       $((-inner_gap+outer_gap_vert+bar_compensation))
bspc config left_padding         $((-inner_gap+outer_gap_hori))
bspc config right_padding        $((-inner_gap+outer_gap_hori))
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config single_monocle       false
bspc config normal_border_color  "#1c1e26"
bspc config focused_border_color "#ad8c79"
bspc config focus_follows_pointer false
bspc config ignore_ewmh_focus     true
bspc config remove_unplugged_monitors true
bspc config remove_disabled_monitors false

# Rules
bspc rule -a Emacs state=tiled
bspc rule -a discord state=tiled desktop=msg follow=off
bspc rule -a Slack state=tiled desktop=msg follow=off
bspc rule -a TelegramDesktop state=tiled desktop=msg follow=off
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a termite state=tiled
bspc rule -a Steam desktop=opt6 follow=off
bspc rule -a mupen64plus state=floating
bspc rule -a org-fenix-llanfair-Llanfair state=floating
bspc rule -a matplotlib state=floating
bspc config external_rules_command "$HOME/.config/bspwm/rules/spotify.sh"


# Launch polybars
~/.screenlayout/Layout.sh
~/.config/polybar/scripts/launch.sh

# Startup
kitty &

uptime=$(cat /proc/uptime | awk '{printf "%0.f\n", $1}')
startup_lock_file=/tmp/bspwm-startup.lock
if [ ! -f $startup_lock_file ]; then
    echo "Running startup block"
    echo "$time" > $startup_lock_file

    # Background applications
    inputplug -d -c ~/on_new_keyboard.sh &
    sxhkd &
    setxkbmap us algtr-intl
    dunst &
    redshift-gtk &

    if [ "$(hostname)" = "station" ]; then
        feh --bg-scale ~/.dotfiles/.img/space.jpg 
        picom --config ~/.config/picom/picom.conf &
        easyeffects --gapplication-service &
        steam-native &
        dropbox &
        mullvad-vpn &
        discord &
        zotero --headless &
    elif [ "$(hostname)" = "shuttle" ]; then
        feh --bg-scale ~/.dotfiles/.img/space.jpg 
        picom --config ~/.config/picom/picom.conf &
        dropbox &
        mullvad-vpn &
        discord-canary &
    elif [ "$(hostname)" = "u5cd01473rc" ]; then
        autorandr --change
        compton &
        dropbox &
        feh --bg-scale ~/Pictures/Wallpapers/ZTWO_wallpaper_1920x1080.png 
        slack &
        teams &
    fi

     # Shared applications
     emacs --with-profile nondoom --daemon=nondoom
     spotify --force-device-scale-factor=0.75 &
     bspc desktop --focus code && kitty &
fi

