(("default" . ((user-emacs-directory . "~/.emacs.doom")
	             (env . (("DOOMDIR" . "~/.config/doom")))
               (server-name . "doom_server")))
 ("nondoom" . ((user-emacs-directory . "~/.emacs.nondoom")
               (server-name . "emacs_server")))
 ("null" . ((user-emacs-directory . "~/.config/null_emacs")
            (server-name . "null_server"))))
