(("default" . ((user-emacs-directory . "~/.config/doom_emacs")
	             (env . (("DOOMDIR" . "~/.config/doom")))
               (server-name . "doom_server")))
 ("nondoom" . ((user-emacs-directory . "~/.config/emacs")
               (server-name . "emacs_server")))
 ("doom" . ((user-emacs-directory . "~/.config/doom_emacs")
               (env . (("DOOMDIR" . "~/.config/doom")))
               (server-name . "doom_server")))
 ("null" . ((user-emacs-directory . "~/.config/null_emacs")
            (server-name . "null_server"))))
